;;--------------------------------;
;; Packages
;;--------------------------------;

(when (>= emacs-major-version 24)
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
  (package-initialize))

(setq package-selected-packages
      '(alert
        auth-source-pass
        auto-complete
        cargo
        circe
        cl-generic
        code-review
        company
        company-go
        company-restclient
        dap-mode
        dash
        dired-du
        dmenu
        docker
        docker-compose-mode
        dockerfile-mode
        dumb-jump
        eat
        eglot
        elfeed
        elpy
        emms
        emojify
        erc-hl-nicks
        erc-image
        eshell-vterm
        evil
        evil-collection
        evil-commentary
        evil-escape
        evil-ledger
        evil-magit
        evil-multiedit
        evil-org
        exwm
        flycheck
        forge
        geiser
        geiser-guile
        go
        go-eldoc
        go-guru
        guix
        hackernews
        helm
        helm-company
        helm-dash
        helm-descbinds
        helm-emms
        helm-exwm
        helm-flycheck
        helm-go-package
        helm-eww
        helm-ls-git
        helm-notmuch
        helm-org
        helm-org-contacts
        helm-pass
        helm-selector
        helm-sly
        helm-system-packages
        helm-tramp
        highlight-indent-guides
        json-mode
        js2-mode
        kubernetes
        kubernetes-evil
        kubernetes-helm
        kubernetes-tramp
        language-detection
        ledger-mode
        leetcode
        lispy
        lispyville
        magit
        magit-todos
        markdown-mode+
        modus-themes
        notmuch
        oauth2
        olivetti
        org
        org-caldav
        org-gcal
        org-journal
        org-modern
        orgit
        org-roam
        pdf-tools
        pinentry
        prettier
        prettier-js
        projectile
        python-black
        rainbow-delimiters
        rainbow-mode
        request
        restclient
        rjsx-mode
        rmsbolt
        rust-mode
        slack
        sly
        sly-asdf
        sly-macrostep
        sly-quicklisp
        smart-mode-line
        svg-tag-mode
        transmission
        tree-sitter
        tree-sitter-langs
        typescript-mode
        websocket
        web-mode
        which-key
        windower
        xelb
        yasnippet
        youtube-dl))

(provide 'init-packages)
