#!/bin/sh

# verbosity / general settings
alias \
    gg="exit" \
    bat="cat /sys/class/power_supply/BAT0/capacity" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkd="mkdir -pv" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner" \
    dmenu_run="dmenu_run -h 40"

# colorize commands
alias \
    ls="ls -sha -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# directory navigation
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../.."

# abbreviate long commands
alias \
    ka="killall" \
    g="git" \
    trem="transmission-remote" \
    YT="youtube-viewer" \
    sdn="sudo shutdown -h now" \
    f="$FILE" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman" \

# enable the `pauseallmpv` command
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

alias wifilist="sudo nmcli device wifi list"
alias wificonnect="sudo nmcli device wifi connect"

alias python="python3"

