Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gdk/UnscaledDPI 196608
Gdk/WindowScalingFactor 1
Xft/DPI 196608
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName ""
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 36
Gtk/CursorThemeName "breeze_cursors"
Net/SoundThemeName "ocean"
Net/IconThemeName "breeze"
Gtk/FontName "Iosevka Comfy 14"
Gtk/MonospaceFontName "Iosevka Comfy 14"